;;; Menu --- Summary:

;;; Commentary:
;;; Code:

(easy-menu-define custom-menu global-map
  "Packages"
  '("Packages"
    
    ("Documentation"
     ["melpa" (describe-package 'melpa)]
     ["use-package" (describe-package 'use-package)]
     ["recentf" (describe-package 'recentf)]
     ["pdf-tools" (describe-package 'pdf-tools)]
     ["god-mode" (describe-package 'god-mode)]
     ["smex (unsupported)" (describe-package 'smex)]
     ["company" (describe-package 'company)]
     ["helpful" (describe-package 'helpful)]
     ["flycheck" (describe-package 'flycheck)]
     ["flyspell" (describe-package 'flyspell)]
     ["treemacs" (describe-package 'treemacs)]
     ["centaur-tabs" (describe-package 'centaur-tabs)]
     ["amx" (describe-package 'amx)]
     ["which-key" (describe-package 'which-key)]
     ["ace-window" (describe-package 'ace-window)]
     ["browse-kill-ring" (describe-package 'browse-kill-ring)]
     ["multiple-cursors" (decribe-package 'multiple-cursors)]
     ["ivy" (decribe-package 'ivy)]
     ["counsel" (describe-package 'counsel)]
     ["swiper" (describe-package 'swiper)]
     ["auctex" (describe-package 'auctex)]
     ["anaconda-mode" (describe-package 'anaconda-mode)]
     ["avy" (decribe-package 'avy)]
     ["anzu" (decribe-package 'anzu)]
     ["latex-preview-pane" (describe-package 'latex-preview-pane)]
     ["marginalia" (describe-package 'marginalia)]
     ["all-the-icons" (describe-package 'all-the-icons)]
     ["all-the-icons-dired" (describe-package 'all-the-icons-dired)]
     ["all-the-icons-completion" (describe-package 'all-the-icons-completion)]
     ["treemacs-all-the-icons" (describe-package 'treemacs-all-the-icons)]
     ["zzz-to-char" (describe-package 'zzz-to-char)]
     ["beacon" (describe-package 'beacon)]
     ["move-text" (describe-package 'move-text)]
     ["dimmer" (describe-package 'dimmer)]
     ["diminish" (describe-package 'diminish)]
     ["json-mode" (describe-package 'json-mode)]
     ["visual-regexp" (describe-package 'visual-regexp)]
     ["visual-regexp-steroids" (describe-package 'visual-regexp-steroids)]
     ["fix-word" (describe-package 'fix-word)]
     ["hl-todo" (describe-package 'hl-todo)]
     ["olivetti" (describe-package 'olivetti)]
     ["aggressive-indent" (describe-package 'aggressive-indent)]
     ["expand region" (describe-package 'expand-region)]
     ["projectile"  (describe-package 'projectile)]
     ["dashboard"  (describe-package 'dashboard)]
     ["yasnippet"  (describe-package 'yasnippet)]
     ["yasnippet-snippets"  (describe-package 'yasnippet-snippets)]
     ["esup" (describe-package 'esup)]
     ["crux" (describe-package 'crux)]
     ["fountain-mode" (describe-package 'fountain-mode)]
     ["prescient" (describe-package 'prescient)]
     ["hydra" (describe-package 'hydra)]
     ["page-break-lines" (describe-package 'page-break-lines)]
     ["iedit" (describe-package 'iedit)]
     )


    ("Utilities 1"
     ["Melpa" 'ignore]
     ["" 'ignore]
     ["package-list-packages" package-list-packages]
     [" " 'ignore]
     ["" 'ignore]
     ["avy" 'ignore]
     ["" 'ignore]
     ["avy-goto-char" avy-goto-char]
     ["avy-goto-word-0" avy-goto-word-0]
     ["avy-goto-line" avy-goto-line]
     ["avy-goto-char-timer" avi-goto-char-timer]
     ["avy-goto-whitespace-end" avy-goto-whitespace-end]
     [" " 'ignore]
     ["all-the-icons" 'ignore]
     ["Backends: dired,completion,treemacs" 'ignore]
     ["" 'ignore]
     ["all-the-icons-insert" all-the-icons-insert]
     ["all-the-icons-insert-all-the-icon" all-the-icons-insert-all-the-icon]
     [" " 'ignore]
     ["" 'ignore]
     ["zzz-to-char" 'ignore]
     ["" 'ignore]
     ["zzz-to-char" zzz-to-char]
     ["zzz-up-to-char" zzz-up-to-char]
     [" " 'ignore]
     ["" 'ignore]
     ["hl-todo" 'ignore]
     [" " 'ignore]
     ["" 'ignore]
     ["hl-todo-mode" hl-todo-mode]
     ["hl-todo-previous" hl-todo-previous]
     ["hl-todo-next" hl-todo-next]
     ["hl-todo-occur" hl-todo-occur]
     ["hl-todo-insert" hl-todo-insert]
     ["" 'ignore]
     ["aggressive-indent" 'ignore]
     ["" 'ignore]
     ["aggressive-indent" aggressive-indent]
     ["aggressive-indent-global-mode" aggressive-indent-global-mode] 
     ["aggressive-indent-indent-defun" aggressive-indent-indent-defun] 
     ["aggressive-indent-indent-region-and-on" aggressive-indent-indent-region-and-on]
     [" " 'ignore]
     ["" 'ignore]
     ["god-mode" 'ignore]
     ["" 'ignore]
     ["god-mode (C-c c)" god-mode]
     ["C-z redo" redo]
     ["C-x z undo" undo])

    
    ("Utilities 2"
     ["Helpful" 'ignore]
     ["" 'ignore]
     ["Helpful Callable" helpful-callable]
     ["Helpful Function" helpful-function]
     ["Helpful Macro" helpful-macro]
     ["Helpful Command" helpful-command]
     ["Helpful Key" helpful-key]
     ["Helpful Variable" helpful-variable]
     ["Helpful at Point" helpful-at-point]
     [" " 'ignore]
     ["" 'ignore]
     ["which-key" 'ignore]
     ["" 'ignore]
     ["which-key-show-full-keymap" which-key-show-full-keymap]
     ["which-key-show-full-major-mode" which-key-show-full-major-mode]
     ["which-key-show-full-minor-mode-keymap" which-key-show-full-minor-mode-keymap]
     ["which-key-show-keymap" which-key-show-keymap]
     [" " 'ignore]
     ["" 'ignore]
     ["browse-kill-ring" 'ignore]
     ["" 'ignore]
     ["browse-kill-ring" browse-kill-ring]
     [" " 'ignore]
     ["" 'ignore]
     ["marginalia" 'ignore]
     ["" 'ignore]
     ["marginalia-cycle" marginalia-cycle]
     [" " 'ignore]
     ["" 'ignore]
     ["Yasnippet" 'ignore]
     ["" 'ignore]
     ["yas-insert-snippet" yas-insert-snippet]
     [" " 'ignore]
     ["" 'ignore]
     ["esup" esup]
     ["" 'ignore]
     ["esup-mode" esup-mode]
     ["emacs-uptime" emacs-uptime]
     ["esup-visit-item" esup-visit-item]
     ["esup-next-result" esup-next-result]
     ["esup-server-create" esup-server-create]
     ["esup-display-results" esup-display-results]
     ["esup-previous-result" esup-previous-result]
     ["elp-instrument-package" elp-instrument-package])

    ("Utilities 3"
     ["move-text" 'ignore]
     ["" 'ignore]  
     ["move-text-up" move-text-up]
     ["move-text-down" move-text-down]
     ["move-text-region" move-text-region]
     ["move-text-line-up" move-text-line-up]
     ["move-text-line-down" move-text-line-down]
     ["move-text-region-up" move-text-region-up]
     ["move-text-region-down" move-text-region-down]
     ["move-text-default-bindings" move-text-default-bindings]
     [" " 'ignore]
     ["" 'ignore]
     ["fix-word" 'ignore]
     ["" 'ignore]
     ["fix-word-upcase" fix-word-upcase]
     ["fix-word-downcase" fix-word-downcase]
     ["fix-word-capitalize" fix-word-capitalize]
     [" " 'ignore]
     ["" 'ignore]
     ["olivetti" 'ignore]
     ["" 'ignore]
     ["olivetti-mode" olivetti-mode]
     ["olivetti-expand" olivetti-expand]
     ["olivetti-shrink" olivetti-shrink]
     ["olivetti-set-width" olivetti-set-width]
     )

    
    ("Configuration"
     ["" 'ignore]
     ["Beacon" 'ignore]
     ["" 'ignore]
     ["beacon-mode" beacon-mode]
     ["beacon-blink" beakon-blink]
     ["" 'ignore]
     ["configuration" 'ignore]
     ["" 'ignore]
     ["beacon-size" beacon-dont-blink-commands]
     ["beacon-color" beacon-dont-blink-commands]
     ["beacon-blink-duration" beacon-dont-blink-commands]
     ["beacon-blink-delay" beacon-dont-blink-commands]
     ["beacon-blink-when-window-scrolls" beacon-dont-blink-commands]
     ["beacon-blink-when-window-changes" beacon-dont-blink-commands]
     ["beacon-blink-when-point-moves" beacon-dont-blink-commands]
     ["beacon-dont-blink-major-modes" beacon-dont-blink-commands]
     ["beacon-dont-blink-predicates" beacon-dont-blink-commands]
     ["beacon-dont-blink-commands" beacon-dont-blink-commands]
     [" " 'ignore]
     ["" 'ignore]
     ["dimmer" 'ignore]
     ["" 'ignore]
     ["dimmer-configure-company-box" dimmer-configure-company-box]
     ["dimmer-configure-gnus" dimmer-configure-gnus]
     ["dimmer-configure-helm" dimmer-configure-helm]
     ["dimmer-configure-hydra" dimmer-configure-hydra]
     ["dimmer-configure-magit" dimmer-configure-magit]
     ["dimmer-configure-org" dimmer-configure-org]
     ["dimmer-configure-posframe" dimmer-configure-posframe]
     ["dimmer-configure-which-key" dimmer-configure-which-key]
     ["" 'ignore]
     ["Customization" 'ignore]
     ["" 'ignore]
     ["dimmer-adjustment-mode" dimmer-adjustment-mode]
     ["dimmer-fraction" dimmer-fraction]
     ["dimmer-buffer-exclusion-regexps" dimmer-buffer-exclusion-regexps]
     ["dimmer-buffer-exclusion-predicates" dimmer-buffer-exclusion-predicates]
     ["dimmer-prevent-dimming-predicates" dimmer-prevent-dimming-predicates]
     ["dimmer-watch-frame-focus-events" dimmer-watch-frame-focus-events]
     ["dimmer-use-colorspace" dimmer-use-colorspace])

    
    ("PDF Tools"
     ["Navigation" 'ignore]
     ["(space/backspace) Scroll Up / Down by page-full" 'ignore]
     ["(C-n/C-p) Scroll Up / Down by line" 'ignore]
     ["(C-f/C-b) Scroll Right / Left" 'ignore]
     ["(</>) Top of Page / Bottom of Page" 'ignore]
     ["(n / p) Next Page / Previous Page" 'ignore]
     ["(M-</M->) First Page / Last Page" 'ignore]
     ["(C-s/C-r) Incremental Search Forward / Backward" 'ignore]
     ["(M-s o) Occur (list all lines containing a phrase)" 'ignore]
     ["(RETURN) Jump to Occur Line" 'ignore]
     ["(F) Pick a Link and Jump" 'ignore]
     ["(f) Incremental Search in Links" 'ignore]
     ["(B/N) History Back / Forward" 'ignore]
     ["(o) Display Outline" 'ignore]
     ["(RETURN) Jump to Section from Outline" 'ignore]
     ["(M-g g) Jump to Page" 'ignore]
     [" " 'ignore]
     ["Display" 'ignore]
     ["(+/-) Zoom in / Zoom out" 'ignore]
     ["(H / W / P) Fit Height / Fit Width / Fit Page" 'ignore]
     ["(s b) Trim margins (set slice to bounding box)" 'ignore]
     ["(s r) Reset margins" 'ignore]
     ["(0) Reset Zoom" 'ignore]
     [" " 'ignore]
     ["Annotations" 'ignore]
     ["(C-c C-a l) List Annotations" 'ignore]
     ["(SPACE) Jump to Annotations from List" 'ignore]
     ["(d) Mark Annotation for Deletion" 'ignore]
     ["(x) Delete Marked Annotations" 'ignore]
     ["(u) Unmark Annotations" 'ignore]
     ["(q) Close Annotation List" 'ignore]
     ["(Left-click) Add and edit annotation" 'ignore]
     [" " 'ignore]
     ["Auctex Syncing wit" 'ignore]
     ["(C-c C-g) jump to PDF location from source" 'ignore]
     ["(C-mouse-1" 'ignore]
     [" jump source location from PDF" 'ignore]
     [" " 'ignore]
     ["Miscellaneous" 'ignore]
     ["(g) Refresh File (e.g., after recompiling source)" 'ignore]
     ["(C-c C-p) Print Fill" 'ignore])

    
    ("Smex and Amx"
     ["smex" smex]
     ["" 'ignore]
     ["smex-describe-function" smex-describe-function]
     ["smex-find-function" smex-find-function]
     ["smex-initialize" smex-initialize]
     ["smex-major-mode-commands" smex-major-mode-commands]
     ["smex-rebuild-cache" smex-rebuild-cache]
     ["smex-save-to-file" smex-save-to-file]
     ["smex-show-unbound-commands" smex-show-unbound-commands]
     ["smex-update" smex-update]
     ["smex-where-is" smex-where-is]
     [" " 'ignore]
     ["amx" 'ignore]
     [" " 'ignore]
     ["amx-describe-function" amx-describe-function]
     ["amx-find-function" amx-find-function]
     ["amx-initialize" amx-initialize]
     ["amx-save-to-file" amx-save-to-file]
     ["amx-show-unbound-commands" amx-show-unbound-commands]
     ["amx-unignore-command" amx-unignore-command]
     ["amx-where-is" amx-where-is]
     ["amx-mode" amx-mode]
     ["amx-major-mode-commands" amx-major-mode-commands])

    
    ("Company"
     ["company-select-next-or-abort" company-select-next-or-abort]
     ["company-select-next" company-select-next]
     ["company-select-previous-or-abort" company-select-previous-or-abort]
     ["company-select-previous" company-select-previous]
     ["company-complete-selection" company-complete-selection]
     ["company-complete-common" company-complete-common]
     ["company-abort" company-abort]
     ["company-show-doc-buffer" company-show-doc-buffer]
     ["company-show-location" company-show-location]
     ["company-active-map" company-active-map]
     ["company-search-map" company-search-map]
     ["company-diag" company-diag]
     [" " 'ignore]
     ["" 'ignore]
     ["Backends" 'ignore]
     ["" 'ignore]
     ["company-dabbrev" 'ignore]
     ["company-auctex" 'ignore]
     ["company-anaconda" 'ignore]
     ["company-prescient" 'ignore])


    ("fly, dabbrev, hippie"
     ["Flycheck" 'ignore]
     ["" 'ignore]
     ["flycheck-mode" flycheck-mode]
     ["flycheck-describe-checker" flycheck-describe-checker]
     ["flycheck-buffer" flycheck-buffer]
     ["flycheck-compile" flycheck-compile]
     ["flycheck-previous-error" flycheck-previous-error]
     ["flycheck-next-error" flycheck-next-error]
     ["flycheck-list-errors" flycheck-list-errors]
     [" " 'ignore]
     ["" 'ignore]
     ["Flyspell" 'ignore]
     ["" 'ignore]
     ["flyspell-mode" flyspell-mode]
     ["flyspell-correct-word" flyspell-correct-word]
     ["flyspell-auto-correct-word" flyspell-auto-correct-word]
     ["flyspell-auto-correct-word-before-point" flyspell-auto-correct-word-before-point]
     ["flyspell-goto-next-error" flyspell-goto-next-error]
     [" " 'ignore]
     ["" 'ignore]
     ["dabbrev" 'ignore]
     ["" 'ignore]
     ["dabbrev-expand" dabbrev-expand]
     ["dabbrev-completion" dabbrev-completion]
     [" " 'ignore]
     ["" 'ignore]
     ["hippie" 'ignore]
     ["" 'ignore]
     ["hippie-expand" hippie-expand])


    ("Tree view and Tabs"
     ["" 'ignore]
     ["Treemacs" 'ignore]
     ["" 'ignore]
     ["treemacs" treemacs]
     ["treemacs-select-window" treemacs-select-window]
     ["treemacs-add-and-display-current-project" treemacs-add-and-display-current-project]
     ["treemacs-delete-other-windows" treemacs-delete-other-windows]
     ["treemacs-select-directory" treemacs-select-directory]
     ["treemacs-bookmark" treemacs-bookmark]
     ["treemacs-find-file" treemacs-find-file]
     ["treemacs-find-tag" treemacs-find-tag]
     ["treemacs-follow-mode (t f)" treemacs-follow-mode]
     [" " 'ignore]
     ["" 'ignore]
     [ "Centaur-Tabs" 'ignore]
     ["" 'ignore]
     ["centaur-tabs-kill-all-buffers-in-current-group" centaur-tabs-kill-all-buffers-in-current-group]
     ["centaur-tabs-kill-match-buffers-in-current-group" centaur-tabs-kill-match-buffers-in-current-group]
     ["centaur-tabs-keep-match-buffers-in-current-group" centaur-tabs-keep-match-buffers-in-current-group]
     ["centaur-tabs-tabs-kill-other-buffers-in-current-group" centaur-tabs-kill-other-buffers-in-current-group]
     ["centaur-tabs-kill-unmodified-buffers-in-current-group" centaur-tabs-kill-unmodified-buffers-in-current-group]
     ["centaur-tabs-select-beg-tab" centaur-tabs-select-beg-tab]
     ["centaur-tabs-select-end-tabselect-beg-tab" centaur-tabs-select-end-tab]
     ["centaur-tabs-forward-group" centaur-tabs-forward-group]
     ["centaur-tabs-backward-group" centaur-tabs-backward-group])


    ("ace-window"
     ["ace-delete-other-windows" ace-delete-other-windows]
     ["ace-delete-window" ace-delete-window]
     ["ace-select-window" ace-select-window]
     ["ace-swap-window" ace-swap-window]
     ["ace-window" ace-window]
     ["ace-window-display-mode" ace-window-display-mode]
     [" " 'ignore]
     ["" 'ignore]
     ["Commands" 'ignore]
     ["" 'ignore]
     ["x - delete window" 'ignore]
     ["m - swap windows" 'ignore]
     ["M - move window" 'ignore]
     ["c - copy window" 'ignore]
     ["j - select buffer" 'ignore]
     ["n - select the previous window" 'ignore]
     ["u - select buffer in the other window" 'ignore]
     ["c - split window fairly in either direction" 'ignore]
     ["v - split window vertically" 'ignore]
     ["b - split window horizontally" 'ignore]
     ["o - maximize current window" 'ignore]
     ["? - show these command bindings" 'ignore])


    ("multiple-cursors"
     ["mc/mark-more-like-this-extended" mc/mark-more-like-this-extended]
     ["mc/mark-next-like-this" mc/mark-next-like-this]
     ["mc/mark-next-lines" mc/mark-next-lines]
     ["mc/mark-previous-like-this" mc/mark-previous-like-this]
     ["mc/mark-previous-lines" mc/mark-previous-lines]
     ["mc/add-cursor-on-click" mc/add-cursor-on-click]
     ["mc/cycle-backward" mc/cycle-backward]
     ["mc/cycle-forward" mc/cycle-forward]
     ["mc/edit-beginnings-of-lines" mc/edit-beginnings-of-lines]
     ["mc/edit-ends-of-lines" mc/edit-ends-of-lines]
     ["mc/edit-lines" mc/edit-lines])


    ("ivy"
     ["ivy-occur-grep-mode" ivy-occur-grep-mode]
     ["ivy-unmark-backward" ivy-unmark-backward]
     ["ivy-occur-next-error" ivy-occur-next-error]
     ["ivy-call-and-recenter" ivy-call-and-recenter]
     ["ivy-previous-line-or-history" ivy-previous-line-or-history]
     ["ivy-mark" ivy-mark]
     ["ivy-mode" ivy-mode]
     ["ivy-resume" ivy-resume]
     ["ivy-unmark" ivy-unmark]
     ["ivy-partial" ivy-partial]
     ["ivy-pop-view" ivy-pop-view]
     ["ivy-push-view" ivy-push-view]
     ["ivy-yank-char" ivy-yank-char]
     ["ivy-occur-mode" ivy-occur-mode]
     [" " 'ignore]
     [""  'ignore]
     ["Backends:"  'ignore]
     [""  'ignore]
     ["ivy-prescient" (describe-package 'ivy-prescient)])


    ("counsel"
     ["counsel-M-x" counsel-M-x]
     ["counsel-descbinds" counsel-descbinds]
     ["counsel-describe-function" counsel-describe-function]
     ["counsel-describe-variable" counsel-describe-variable]
     ["counsel-apropos" counsel-apropos]
     ["counsel-describe-face" counsel-describe-face]
     ["counsel-faces" counsel-faces]
     ["counsel-find-file" counsel-find-file]
     ["counsel-find-library" counsel-find-library]
     ["counsel-imenu" counsel-imenu]
     ["counsel-load-library" counsel-load-library]
     ["counsel-load-theme" counsel-load-theme]
     ["counsel-yank-pop" counsel-yank-pop]
     ["counsel-info-lookup-symbol" counsel-info-lookup-symbol]
     ["counsel-mark-ring" counsel-mark-ring]
     ["counsel-bookmark" counsel-bookmark])


    ("swiper"
     ["swiper-backward" swiper-backward]
     ["swiper-isearch-C-r" swiper-isearch-C-r]
     ["swiper-from-isearch" swiper-from-isearch]
     ["swiper-isearch-toggle" swiper-isearch-toggle]
     ["swiper-thing-at-point" swiper-thing-at-point]
     ["swiper-isearch-backward" swiper-isearch-backward]
     ["swiper-all-thing-at-point" swiper-all-thing-at-point]
     ["swiper-recenter-top-bottom" swiper-recenter-top-bottom]
     ["swiper-isearch-thing-at-point" swiper-isearch-thing-at-point]
     ["swiper" swiper]
     ["swiper-mc" swiper-mc]
     ["swiper-C-s" swiper-C-s]
     ["swiper-all" swiper-all]
     ["swiper-multi" swiper-multi]
     ["swiper-isearch (C-s)" swiper-isearch (C-s)])


    ("anaconda-mode"
     ["anaconda-mode-complete" anaconda-mode-complete]
     ["anaconda-mode-find-definitions" anaconda-mode-find-definitions]
     ["anaconda-mode-find-definitions-other-window" anaconda-mode-find-definitions-other-window]
     ["anaconda-mode-find-definitions-other-frame" anaconda-mode-find-definitions-other-frame]
     ["anaconda-mode-find-assignments" anaconda-mode-find-assignments]
     ["anaconda-mode-find-assignments-other-window" anaconda-mode-find-assignments-other-window]
     ["anaconda-mode-find-assignments-other-frame" anaconda-mode-find-assignments-other-frame]
     ["anaconda-mode-find-references" anaconda-mode-find-references]
     ["anaconda-mode-find-references-other-window" anaconda-mode-find-references-other-window]
     ["anaconda-mode-find-references-other-frame" anaconda-mode-find-references-other-frame]
     ["xref-pop-marker-stack" xref-pop-marker-stack]
     ["anaconda-mode-show-doc" anaconda-mode-show-doc])


    ("anzu"
     ["anzu-replace-at-cursor-thing" anzu-replace-at-cursor-thing]
     ["anzu-mode" anzu-mode]
     ["anzu-query-replace" anzu-query-replace]
     ["anzu-query-replace-regexp" anzu-query-replace-regexp]
     ["anzu-isearch-query-replace" anzu-isearch-query-replace]
     ["anzu-query-replace-at-cursor" anzu-query-replace-at-cursor]
     ["anzu-isearch-query-replace-regexp" anzu-isearch-query-replace-regexp]
     ["anzu-query-replace-at-cursor-thing" anzu-query-replace-at-cursor-thing])


    ("auctex"
     ["TeX-command-run-all" TeX-command-run-all]
     ["TeX-command-buffer" TeX-command-buffer]
     ["TeX-command-master" TeX-command-master]
     ["TeX-save-document" TeX-save-document]
     ["TeX-uncomment" TeX-uncomment]
     ["TeX-comment-or-uncomment-paragraph" TeX-comment-or-uncomment-paragraph]
     ["TeX-comment-or-uncomment-paragraph" TeX-comment-or-uncomment-paragraph]
     ["LaTeX-mark-section" LaTeX-mark-section]
     ["LaTeX-mark-environment" LaTeX-mark-environment]
     ["comment-or-uncomment-region" comment-or-uncomment-region]
     ["LaTeX-insert-item" LaTeX-insert-item]
     ["LaTeX-section" LaTeX-section]
     ["LaTeX-command-section" LaTeX-command-section]
     ["LaTeX-close-environment" LaTeX-close-environment]
     ["TeX-master-file-ask" TeX-master-file-ask]
     ["LaTeX-math-mode" LaTeX-math-mode]
     ["preview-buffer" preview-buffer]
     ["preview-document" preview-document]
     ["preview-environment" preview-environment]
     ["preview-at-point" preview-at-point]
     ["preview-region" preview-region]
     ["preview-section" preview-section]
     ["LaTeX-fill-environment" LaTeX-fill-environment]
     ["LaTeX-fill-paragraph" LaTeX-fill-paragraph]
     ["LaTeX-fill-region" LaTeX-fill-region]
     ["LaTeX-fill-section" LaTeX-fill-section])


    ("json-mode"
     ["jsons-print-path" jsons-print-path]
     ["json-pretty-print" json-pretty-print]
     ["json-mode-beautify" json-mode-beautify]
     ["json-mode-kill-path" json-mode-kill-path]
     ["json-mode-show-path" json-mode-show-path]
     ["json-pretty-print-buffer" json-pretty-print-buffer]
     ["json-pretty-print-ordered" json-pretty-print-ordered]
     ["json-pretty-print-buffer-ordered" json-pretty-print-buffer-ordered]
     ["" 'ignore]
     ["Bindings" 'ignore]
     ["" 'ignore]
     ["C-c C-f: format region" 'ignore]
     ["C-c C-p: display path" 'ignore]
     ["C-c P: copy a path" 'ignore]
     ["C-c C-t: Toggle true/false" 'ignore]
     ["C-c C-k: Replace sexp" 'ignore]
     ["C-c C-i: Increment number" 'ignore]
     ["C-c C-d: Decrement number" 'ignore])


    ("visual-regexp+steroids"
     ["vr/mc-mark" vr/mc-mark]
     ["vr/replace" vr/replace]
     ["vr/query-replace" vr/query-replace]
     ["vr/select-mc-mark" vr/select-mc-mark]
     ["vr/select-replace" vr/select-replace]
     ["vr/isearch-forward" vr/isearch-forward]
     ["vr/isearch-backward" vr/isearch-backward])


    ("expand-region"
     ["er/mark-url" er/mark-url]
     ["er/mark-word" er/mark-word]
     ["er/mark-defun" er/mark-defun]
     ["er/mark-email" er/mark-email]
     ["er/mark-symbol" er/mark-symbol]
     ["er/mark-comment" er/mark-comment]
     ["er/expand-region" er/expand-region]
     ["er/mark-inner-tag" er/mark-inner-tag]
     ["er/mark-outer-tag" er/mark-outer-tag])


    ("projectile"
     ["projectile-find-file" projectile-find-file]
     ["projectile-find-file-in-directory" projectile-find-file-in-directory]
     ["projectile-dired" projectile-dired]
     ["projectile-find-dir" projectile-find-dir]
     ["projectile-recentf" projectile-recentf]
     ["projectile-replace" projectile-replace]
     ["projectile-commander" projectile-commander]
     ["projectile-commander-help-buffer" projectile-commander-help-buffer]
     ["projectile-run-shell" projectile-run-shell]
     ["projectile-run-project" projectile-run-project]
     ["projectile-kill-buffers" projectile-kill-buffers]
     ["projectile-test-project" projectile-test-project]
     ["projectile-display-buffer" projectile-display-buffer]
     ["projectile-display-project" projectile-display-project]
     ["projectile-find-other-file" projectile-find-other-file]
     ["projectile-switch-to-buffer" projectile-switch-to-buffer]
     ["projectile-save-project-buffers" projectile-save-project-buffers])


    ("dashboard"
     ["dashboard-mode" dashboard-mode]
     ["dashboard-return" dashboard-return]
     ["dashboard-mouse-1" dashboard-mouse-1]
     ["dashboard-next-line" dashboard-next-line]
     ["dashboard-next-section" dashboard-next-section]
     ["dashboard-previous-line" dashboard-previous-line]
     ["dashboard-refresh-buffer" dashboard-refresh-buffer]
     ["dashboard-previous-section" dashboard-previous-section]
     ["dashboard-insert-startupify-lists" dashboard-insert-startupify-lists]
     [" " 'ignore]
     ["" 'ignore]
     ["Shortcuts" 'ignore]
     ["" 'ignore]
     ["Tab Or C-i Next Item" 'ignore]
     ["Shift-Tab Previous Item" 'ignore]
     ["Return/Mouse Click/C-m Open" 'ignore]
     ["r Recent files" 'ignore]
     ["m Bookmarks" 'ignore]
     ["p Projects" 'ignore]
     ["a Org-Mode Agenda" 'ignore]
     ["e Registers" 'ignore]
     ["g Refresh contents" 'ignore]
     ["{ Previous section" 'ignore]
     ["} Next section" 'ignore])


    ("crux"
     ["crux-move-beginning-of-line" crux-move-beginning-of-line]
     ["crux-open-with" crux-open-with]
     ["crux-smart-kill-line" crux-smart-kill-line]
     ["crux-smart-open-line-above" crux-smart-open-line-above]
     ["crux-smart-open-line" crux-smart-open-line]
     ["crux-cleanup-buffer-or-region" crux-cleanup-buffer-or-region]
     ["crux-recentf-find-file" crux-recentf-find-file]
     ["crux-recentf-find-directory" crux-recentf-find-directory]
     ["crux-view-url" crux-view-url]
     ["crux-eval-and-replace" crux-eval-and-replace]
     ["crux-transpose-windows" crux-transpose-windows]
     ["crux-delete-file-and-buffer" crux-delete-file-and-buffer]
     ["crux-copy-file-preserve-attributes" crux-copy-file-preserve-attributes]
     ["crux-duplicate-current-line-or-region" crux-duplicate-current-line-or-region]
     ["crux-duplicate-and-comment-current-line-or-region" crux-duplicate-and-comment-current-line-or-region]
     ["crux-rename-file-and-buffer" crux-rename-file-and-buffer]
     ["crux-visit-term-buffer" crux-visit-term-buffer]
     ["crux-kill-other-buffers" crux-kill-other-buffers]
     ["crux-indent-defun" crux-indent-defun]
     ["crux-indent-rigidly-and-copy-to-clipboard" crux-indent-rigidly-and-copy-to-clipboard]
     ["crux-find-user-init-file" crux-find-user-init-file]
     ["crux-find-user-custom-file" crux-find-user-custom-file]
     ["crux-find-shell-init-file" crux-find-shell-init-file]
     ["crux-top-join-line" crux-top-join-line]
     ["crux-kill-whole-line" crux-kill-whole-line]
     ["crux-kill-line-backwards" crux-kill-line-backwards]
     ["crux-kill-and-join-forward" crux-kill-and-join-forward]
     ["crux-kill-buffer-truename" crux-kill-buffer-truename]
     ["crux-ispell-word-then-abbrev" crux-ispell-word-then-abbrev]
     ["crux-upcase-region" crux-upcase-region]
     ["crux-downcase-region" crux-downcase-region]
     ["crux-capitalize-region" crux-capitalize-region]
     ["crux-other-window-or-switch-buffer" crux-other-window-or-switch-buffer])

    ("iedit"
     ["iedit-mode" iedit-mode]
     ["iedit-start-kmacro" iedit-start-kmacro]
     ["iedit-rectangle-mode" iedit-rectangle-mode]
     ["iedit-next-occurrence" iedit-next-occurrence]
     ["iedit-prev-occurrence" iedit-prev-occurrence]
     ["iedit-toggle-buffering" iedit-toggle-buffering]
     ["iedit-blank-occurrences" iedit-blank-occurrences]
     ["iedit-mode-from-isearch" iedit-mode-from-isearch]
     ["iedit-switch-to-mc-mode" iedit-switch-to-mc-mode]
     ["iedit-delete-occurrences" iedit-delete-occurrences]
     ["iedit-number-occurrences" iedit-number-occurrences]
     ["iedit-upcase-occurrences" iedit-upcase-occurrences]
     ["iedit-end-and-call-kmacro" iedit-end-and-call-kmacro]
     ["iedit-replace-occurrences" iedit-replace-occurrences]
     ["iedit-downcase-occurrences" iedit-downcase-occurrences]
     ["iedit-goto-last-occurrence" iedit-goto-last-occurrence]
     ["iedit-help-for-occurrences" iedit-help-for-occurrences]
     ["iedit-goto-first-occurrence" iedit-goto-first-occurrence]
     ["iedit-mode-toggle-on-function" iedit-mode-toggle-on-function]
     ["iedit-show/hide-context-lines" iedit-show/hide-context-lines]
     ["iedit-execute-last-modification" iedit-execute-last-modification]
     ["iedit-show/hide-occurrence-lines" iedit-show/hide-occurrence-lines])
    
    ))
;;; pull-down-packages ends here
